"use client";
import {useEffect,useState} from "react";
import FlowBuilder from "./components/FlowBuilder";
import {Module} from "./components/AdminModules";
type View="overview"|"bot"|"contacts"|"teams"|"hours"|"reports"|"public"|"install"|"settings"|"history"|"users";
export default function Home(){const[view,setView]=useState<View>("overview"),[user,setUser]=useState<any>(null);useEffect(()=>{fetch("/api/auth/me").then(async r=>{if(r.ok)setUser((await r.json()).user);else location.href="/login"})},[]);if(!user)return <main className="admin-loading">Carregando painel...</main>;return <main className="shell"><aside className="sidebar"><div className="brand"><b>A</b><strong>Atende<span>Fácil</span></strong></div><nav><Nav on={()=>setView("overview")} active={view==="overview"} icon="◫" text="Visão geral"/><Nav on={()=>setView("bot")} active={view==="bot"} icon="✦" text="Meu bot"/><Nav on={()=>setView("contacts")} active={view==="contacts"} icon="◎" text="Contatos"/><Nav on={()=>setView("teams")} active={view==="teams"} icon="⌁" text="Equipes"/><Nav on={()=>setView("hours")} active={view==="hours"} icon="◷" text="Horários"/><Nav on={()=>setView("reports")} active={view==="reports"} icon="↗" text="Relatórios"/><small>CANAIS</small><Nav on={()=>setView("public")} active={view==="public"} icon="⌂" text="Página de atendimento"/><Nav on={()=>setView("install")} active={view==="install"} icon="</>" text="Colocar no meu site"/><small>ADMINISTRAÇÃO</small><Nav on={()=>setView("settings")} active={view==="settings"} icon="⚙" text="Configurações"/><Nav on={()=>setView("users")} active={view==="users"} icon="♙" text="Usuários"/></nav><div className="sidebar-end"><Nav on={()=>setView("history")} active={view==="history"} icon="◴" text="Histórico"/><div className="profile"><i>{user.name.slice(0,2).toUpperCase()}</i><span><b>{user.name}</b><small>{user.role==="ADMIN"?"Administrador":"Editor"}</small></span></div></div></aside><section className="workspace">{view==="bot"?<FlowBuilder/>:view==="public"?<PublicPage/>:view==="install"?<Install/>:<Module view={view}/>}</section></main>}
function Nav({on,active,icon,text}:{on:()=>void;active?:boolean;icon:string;text:string}){return <button onClick={on} className={active?"active":""}><i>{icon}</i>{text}</button>}
function PublicPage(){return <div className="public"><header><div className="brand"><b>A</b><strong>Atende<span>Fácil</span></strong></div><span>● Atendimento online</span></header><main><section><small>ATENDIMENTO AUTOMÁTICO</small><h1>Respostas rápidas,<br/>sem complicação.</h1><p>Navegue pelas opções do bot pelo navegador. Sem cadastro, sem aplicativo e sem WhatsApp.</p><div>✓ Sem cadastro　 ✓ Disponível 24 horas　 ✓ Protocolo automático</div></section><aside><i>✦</i><h2>Inicie o atendimento</h2><p>Nosso assistente apresenta as opções e entrega informações, vídeos e documentos automaticamente.</p><a className="public-start" href="/atendimento">Começar agora →</a><small>● Bot disponível agora</small></aside></main></div>}
function Install(){const[copied,setCopied]=useState("");const base="https://atende-facil.jotaunior.chatgpt.site",floating=`<script src="${base}/widget.js" data-chat="principal"></script>`,embedded=`<iframe src="${base}/atendimento?widget=1" title="Atendimento" style="width:100%;height:650px;border:0;border-radius:16px" allow="clipboard-write"></iframe>`;function copy(value:string,type:string){navigator.clipboard?.writeText(value);setCopied(type)}return <><header className="module-head"><div><small>CANAIS</small><h1>Colocar no meu site</h1><p>Escolha o formato e copie o código pronto.</p></div></header><div className="install"><article><i>1</i><section><h2>Botão flutuante</h2><p>Abre e fecha no canto da página.</p><pre>{floating}</pre><button className="primary" onClick={()=>copy(floating,"floating")}>{copied==="floating"?"✓ Código copiado":"Copiar código"}</button></section></article><article><i>2</i><section><h2>Área incorporada e sempre aberta</h2><p>O atendimento ocupa 100% da largura e altura definidas no seu site.</p><pre>{embedded}</pre><button className="primary" onClick={()=>copy(embedded,"embedded")}>{copied==="embedded"?"✓ Código copiado":"Copiar código"}</button><div><span>Altere apenas height:650px</span><span>Responsivo</span><span>Sempre maximizado</span></div></section></article></div></>}
