"use client";
import {useEffect,useRef,useState} from "react";import {appPath} from "../lib/paths";
import Linkify from "../components/Linkify";
type Kind="message"|"menu"|"image"|"video"|"audio"|"pdf"|"link"|"input"|"team"|"hours"|"end";
type Node={id:string;title:string;kind:Kind;text:string;url?:string;caption?:string;next?:string;options?:{id:string;label:string;target:string}[];team?:string};
type Flow={startId:string;nodes:Node[]};type Line={sender:"BOT"|"VISITOR"|"AGENT";content:string};
export default function Atendimento(){
 const[flow,setFlow]=useState<Flow|null>(null),[current,setCurrent]=useState(""),[started,setStarted]=useState(false),[conversation,setConversation]=useState<any>(null),[lines,setLines]=useState<Line[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[widget,setWidget]=useState(false),[rating,setRating]=useState<number|null>(null),[loadError,setLoadError]=useState("");const tracked=useRef(new Set<string>());
 async function loadFlow(){setLoadError("");try{const r=await fetch(appPath("/api/flow"),{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();if(!d.flow?.config?.nodes?.length)throw new Error();setFlow(d.flow.config);setCurrent(d.flow.config.startId)}catch{setLoadError("Não foi possível carregar o atendimento.")}}
 useEffect(()=>{setWidget(new URLSearchParams(window.location.search).get("widget")==="1");loadFlow()},[]);const node=flow?.nodes.find(n=>n.id===current);
 async function event(action:string,details:unknown){if(!conversation)return;await fetch(appPath(`/api/conversations/${conversation.id}/event`),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:conversation.visitorToken,action,details})})}
 useEffect(()=>{if(!started||!conversation||!node||tracked.current.has(node.id))return;tracked.current.add(node.id);event("FLOW_NODE",{nodeId:node.id,title:node.title,kind:node.kind});if(node.kind==="end")event("FLOW_END",{nodeId:node.id,title:node.title})},[started,conversation,node?.id]);
 async function start(){if(!flow)return;setBusy(true);const r=await fetch(appPath("/api/conversations"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({origin:widget?"WIDGET":"PUBLIC_PAGE",flow:true})});const d=await r.json();setConversation(d.conversation);setStarted(true);setCurrent(flow.startId);setLines([]);setRating(null);tracked.current.clear();setBusy(false)}
 async function record(content:string){if(!conversation)return;await fetch(appPath(`/api/conversations/${conversation.id}/messages`),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:conversation.visitorToken,content})})}
 function go(target?:string,label?:string){if(label){setLines(l=>[...l,{sender:"VISITOR",content:label}]);record(label)}if(target)setCurrent(target)}
 function submit(){if(!text.trim()||!node)return;const value=text.trim();setText("");setLines(l=>[...l,{sender:"VISITOR",content:value}]);record(value);if(node.next)setCurrent(node.next)}
 function downloadUrl(url:string){return `${url}${url.includes("?")?"&":"?"}download=1`}
 async function rate(value:number){setRating(value);await event("RATING",{value,nodeId:node?.id})}
 function media(n:Node){if(!n.url)return null;if(n.kind==="image")return <img className="visitor-media" src={n.url} alt={n.caption||"Imagem enviada pelo atendimento"}/>;if(n.kind==="video")return <video className="visitor-media" controls src={n.url}/>;if(n.kind==="audio")return <audio controls src={n.url}/>;if(n.kind==="pdf")return <div className="visitor-file-actions"><a className="visitor-file" href={n.url} target="_blank" rel="noopener noreferrer">📄 {n.caption||"Visualizar PDF"}</a><a className="visitor-download" href={downloadUrl(n.url)} onClick={()=>event("DOWNLOAD",{nodeId:n.id,url:n.url,type:"pdf"})}>Baixar arquivo</a></div>;if(n.kind==="link")return <a className="visitor-file" href={n.url} target="_blank" rel="noopener noreferrer">🔗 {n.caption||"Abrir link"}</a>;return null}
 function nodeView(n:Node){return <><div className="visitor-message">{media(n)}<span><Linkify text={n.text}/></span><small>agora</small></div>{n.kind==="menu"&&<div className="visitor-options">{n.options?.map(o=><button key={o.id} onClick={()=>go(o.target,o.label)}>{o.label}</button>)}</div>}{n.kind==="input"&&<div className="visitor-reply"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Digite sua resposta"/><button onClick={submit}>➤</button></div>}{n.kind==="team"&&<div className="queue-status">🏷️ Categoria: {n.team||"Atendimento"}</div>}{n.kind==="end"&&<div className="rating">{rating===null?<><span>Esta informação foi útil?</span><button onClick={()=>rate(1)}>😞</button><button onClick={()=>rate(3)}>😐</button><button onClick={()=>rate(5)}>😊</button></>:<b>Obrigado pela avaliação! {rating===5?"😊":rating===3?"😐":"😞"}</b>}<button className="restart" onClick={start}>Novo atendimento</button></div>}{n.kind!=="menu"&&n.kind!=="input"&&n.kind!=="end"&&n.next&&<button className="visitor-continue" onClick={()=>go(n.next)}>Continuar →</button>}</>}
 return <main className={`visitor-page${widget?" widget":""}`}><header><a href={appPath("/")} className="visitor-brand"><b>A</b><strong>Atende<span>Fácil</span></strong></a><span className="online">● Bot disponível</span></header><section className="visitor-layout"><div className="visitor-intro"><small>ATENDIMENTO AUTOMÁTICO</small><h1>Como podemos<br/>ajudar você?</h1><p>Escolha as opções e receba as informações pelo navegador. Sem cadastro, aplicativo ou WhatsApp.</p><div>✓ Acesso anônimo<br/>✓ Respostas automáticas<br/>✓ Histórico pelo protocolo</div></div><div className="visitor-chat"><header><i>A</i><span><b>Assistente virtual</b><small>● disponível agora</small></span>{conversation&&<em>{conversation.protocol}</em>}</header><section>{!started?<div className="visitor-empty"><i>✦</i><h2>Inicie o atendimento</h2><p>Nosso assistente apresentará opções e entregará as informações automaticamente.</p>{loadError?<><b className="load-error">{loadError}</b><button onClick={loadFlow}>Tentar novamente</button></>:<button disabled={busy||!flow} onClick={start}>{!flow?"Carregando...":busy?"Iniciando...":"Começar atendimento →"}</button>}</div>:<><div className="chat-date">HOJE</div>{lines.map((l,i)=><div key={i} className={l.sender==="VISITOR"?"visitor-message mine":"visitor-message"}><Linkify text={l.content}/><small>agora</small></div>)}{node&&nodeView(node)}</>}</section></div></section></main>
}
